# ================================
# Appearance
# ================================

# Cursorword
# https://github.com/itchyny/vim-cursorword
[[plugins]]
repo = 'itchyny/vim-cursorword'
lazy = 0
hook_add = '''
  autocmd MyAutoCmd FileType nerdtree let b:cursorword = 0
'''

# lualine.nvim
# https://github.com/nvim-lualine/lualine.nvim
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# lazy = 0
# hook_add = 'source $NVIM_PLUGINS/lualine.rc.lua'

# ================================
# File Navigation
# ================================

# ZFZ
# https://github.com/junegunn/fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --bin'
# We need only executable
merged = 0
lazy = 1
[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FzfAg', 'Files', 'GFiles', 'Buffers', 'Ag', 'Tags', 'BTags', 'Marks', 'Windows', 'History:', 'Maps', 'Filetypes']
hook_source = 'source $NVIM_PLUGINS/fzf.vim'

# ================================
# Moving & Searching
# ================================

# EasyMotion
# https://github.com/easymotion/vim-easymotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source $NVIM_PLUGINS/easymotion.vim'

# Hop
# https://github.com/phaazon/hop.nvim
[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = 'source $NVIM_PLUGINS/hop.rc.lua'

# Incsearch
# https://github.com/haya14busa/incsearch.vim
[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_func = 'incsearch#'
[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'vim-easymotion']
on_map = '<Plug>(incsearch-easymotion-'
[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = 'incsearch.vim'
on_map = '<Plug>(incsearch-fuzzy-'

# ================================
# Editing
# ================================

# EasyAlign
# https://github.com/junegunn/vim-easy-align
[[plugins]]
repo = 'junegunn/vim-easy-align'
depends = 'vim-repeat'
on_map = ['<Plug>(EasyAlign', '<Plug>(LiveEasyAlign)']

# EditorConfig
# https://github.com/editorconfig/editorconfig-vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_event = 'InsertEnter'
hook_add = '''
  let g:EditorConfig_disable_rules = [
    \ 'insert_final_newline',
    \ 'trim_trailing_whitespace',
    \ ]
'''

# Fugitive
# https://github.com/tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Git'
on_event = 'BufEnter'

# GitGutter
# https://github.com/airblade/vim-gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
depends = 'vim-repeat'
on_func = 'gitgutter#'
on_event = 'BufEnter'
hook_add = '''
  let g:gitgutter_map_keys = 0
'''

# Peekaboo
# https://github.com/junegunn/vim-peekaboo
[[plugins]]
repo = 'junegunn/vim-peekaboo'
lazy = 1
hook_add = '''
  autocmd MyAutoCmd BufEnter * let b:peekaboo_on = 1
  let g:peekaboo_delay = 1750
'''

# Signature
# https://github.com/kshenoy/vim-signature
[[plugins]]
repo = 'kshenoy/vim-signature'
on_event = 'BufEnter'

# SplitJoin
# https://github.com/AndrewRadev/splitjoin.vim
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_map = '<Plug>Splitjoin'
hook_add = '''
  let g:splitjoin_join_mapping = 0
  let g:splitjoin_split_mapping = 0
'''

# UltiSnips
# https://github.com/SirVer/ultisnips
[[plugins]]
repo = 'SirVer/ultisnips'
on_event = 'InsertEnter'
on_ft = 'snippets'
hook_add = '''
  let g:UltiSnipsSnippetDirectories = [$NVIM_SNIPPETS]
  let g:UltiSnipsEnableSnipMate = 0
  autocmd MyAutoCmd BufWritePost *.snippets call UltiSnips#RefreshSnippets()
'''

# ================================
# Utility
# ================================

# Repeat
# https://github.com/tpope/vim-repeat
[[plugins]]
repo = 'tpope/vim-repeat'
lazy = 1

# LSP
# https://github.com/neovim/nvim-lspconfig
# https://github.com/williamboman/nvim-lsp-installer
# https://github.com/tami5/lspsaga.nvim
# https://github.com/onsails/lspkind-nvim
[[plugins]]
repo = 'tami5/lspsaga.nvim'
hook_add = 'source $NVIM_PLUGINS/lspsaga.rc.lua'
[[plugins]]
repo = 'onsails/lspkind-nvim'
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['lspsaga.nvim', 'lspkind-nvim']
# on_ft = ['javascript', 'typescript', 'typescriptreact', 'typescript.tsx' 'python']
hook_add = 'source $NVIM_PLUGINS/lspconfig.rc.lua'
[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
depends = []
# hook_add = 'source $NVIM_PLUGINS/lsp-installer.rc.lua'

# CMP Completion
# https://github.com/hrsh7th/nvim-cmp
# https://github.com/hrsh7th/cmp-buffer
# https://github.com/hrsh7th/cmp-nvim-lsp
# https://github.com/L3MON4D3/LuaSnip
# https://github.com/ray-x/cmp-treesitter
# https://github.com/quangnguyen30192/cmp-nvim-ultisnips
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'ray-x/cmp-treesitter'
[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
depends = ['nvim-cmp']
hook_add = 'source $NVIM_PLUGINS/cmp-nvim-ultisnips.rc.lua'
[[plugins]]
repo = 'L3MON4D3/LuaSnip'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['cmp-buffer', 'cmp-treesitter', 'lspkind-nvim', 'nvim-lspconfig', 'L3MON4D3/LuaSnip']
# on_ft = ['javascript', 'typescript', 'typescriptreact', 'typescript.tsx' 'python']
hook_add = '''
  source $NVIM_PLUGINS/cmp.rc.lua
  set completeopt=menuone,noinsert,noselect
'''
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = ['nvim-lspconfig']

# symbols-outline.nvim
# https://github.com/simrat39/symbols-outline.nvim
[[plugins]]
repo = 'simrat39/symbols-outline.nvim'
hook_add = 'source $NVIM_PLUGINS/symbols-outline.rc.lua'

# ================================
# Language
# ================================

# AppleScript .applescript
# https://github.com/dearrrfish/vim-applescript
# [[plugins]]
# repo = 'dearrrfish/vim-applescript'
# on_ft = 'applescript'

# CSS3 .css
# https://github.com/hail2u/vim-css3-syntax
# https://github.com/ap/vim-css-color
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
hook_add = '''
  autocmd MyAutoCmd FileType css setlocal iskeyword+=-
'''
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'stylus', 'html', 'javascript', 'typescript']

# Dockerfile docker-compose.yml
# https://github.com/ekalinin/Dockerfile.vim
# [[plugins]]
# repo = 'ekalinin/Dockerfile.vim'
# on_ft = ['Dockerfile', 'docker-compose']

# HTML5 .html .htm
# https://github.com/othree/html5.vim
# https://github.com/mattn/emmet-vim
# [[plugins]]
# repo = 'othree/html5.vim'
# on_ft = 'html'
# hook_add = '''
#   let g:html5_event_handler_attributes_complete = 0
#   let g:html5_rdfa_attributes_complete = 0
#   let g:html5_microdata_attributes_complete = 0
#   let g:html5_aria_attributes_complete = 0
# '''
# [[plugins]]
# repo = 'mattn/emmet-vim'
# on_cmd = 'Emmet'
# # on_ft = ['html', 'javascript']
# # on_map = '<Plug>(emmet-'
# hook_add = '''
#   let g:user_emmet_install_global = 1
#   let g:user_emmet_leader_key = '<C-q>'
#   " autocmd FileType javascript EmmetInstall
# '''

# JavaScript .js
# TypeScript .ts
# https://github.com/pangloss/vim-javascript
# https://github.com/leafgarland/typescript-vim
# https://github.com/gavocanov/vim-js-indent
# https://github.com/mxw/vim-jsx
# https://github.com/MaxMEllon/vim-jsx-pretty
# https://github.com/Quramy/vim-js-pretty-template
# https://github.com/windwp/nvim-ts-autotag
# [[plugins]]
# repo = 'pangloss/vim-javascript'
# lazy = 0 # on_ft = 'javascript'
# hook_add = '''
#   let g:javascript_plugin_flow = 1
# '''
# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft = ['typescript']
# hook_add = '''
#   let g:typescript_indent_disable = 1
# '''
# [[plugins]]
# repo = 'gavocanov/vim-js-indent'
# depends = ['vim-javascript']
# on_ft = ['javascript', 'typescript']
# [[plugins]]
# repo = 'mxw/vim-jsx'
# depends = ['vim-javascript', 'splitjoin.vim']
# lazy = 1 # on_ft = 'javascript'
# [[plugins]]
# repo = 'MaxMEllon/vim-jsx-pretty'
# depends = 'vim-javascript'
# on_ft = ['javascript', 'typescript']
# hook_add = '''
#   let g:vim_jsx_pretty_colorful_config = 0
#   let g:vim_jsx_pretty_highlight_close_tag = 0
# '''
# [[plugins]]
# repo = 'Quramy/vim-js-pretty-template'
# depends = ['vim-pug', 'vim-jsx']
# on_ft = ['javascript', 'typescript']
# hook_source = '''
#   call jspretmpl#register_tag('pug', 'pug')
#   call jspretmpl#register_tag('yaml', 'yaml')
#   autocmd MyAutoCmd FileType javascript.* JsPreTmpl
# '''
[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = ['javascript', 'typescriptreact', 'typescript.tsx']
# hook_source = '''
#   lua <<EOF
#   require('nvim-ts-autotag').setup()
#   EOF
# '''

# Markdown .md
# https://github.com/plasticboy/vim-markdown
# https://github.com/JamshedVesuna/vim-markdown-preview
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# on_ft = 'markdown'
# hook_add = '''
#   let g:vim_markdown_no_default_key_mappings = 1
#   let g:vim_markdown_new_list_item_indent = 2
#   let g:vim_markdown_folding_disabled = 1
#   let g:vim_markdown_conceal = 0
# '''
[[plugins]]
repo = 'JamshedVesuna/vim-markdown-preview'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_preview_toggle = -1
  let g:vim_markdown_preview_github = 1
  let g:vim_markdown_preview_browser = 'Safari'
'''

# MDX .mdx
# https://github.com/jxnblk/vim-mdx-js
# [[plugins]]
# repo = 'jxnblk/vim-mdx-js'
# on_ft = 'mdx'

# Nginx conf
# https://github.com/chr4/nginx.vim
# [[plugins]]
# repo = 'chr4/nginx.vim'
# on_ft = 'nginx'

# PlantUML .uml
# https://github.com/aklt/plantuml-syntax
# https://github.com/tyru/open-browser.vim
# https://github.com/weirongxu/plantuml-previewer.vim
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['uml', 'plantuml']
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:openbrowser_browser_commands = [
    \ {'name': 'open', 'args': ['{browser}', '-a', 'Safari', '{uri}'], 'background': 0}
    \ ]
'''
[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
depends = 'open-browser.vim'
on_cmd = ['PlantumlOpen', 'PlantumlSave']
hook_add = '''
  let g:plantuml_previewer#plantuml_jar_path = get(
    \  matchlist(system('cat `which plantuml` | grep plantuml.jar'), '\v.*\s[''"]?(\S+plantuml\.jar).*'),
    \  1,
    \  0
    \)
'''

# Prisma .prisma
# https://github.com/pantharshit00/vim-prisma
[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_ft = 'prisma'

# Pug .pug
# https://github.com/digitaltoad/vim-pug
# [[plugins]]
# repo = 'digitaltoad/vim-pug'
# depends = ['html5.vim', 'vim-javascript', 'vim-css3-syntax']
# on_ft = 'pug'

# Python .py
# https://github.com/davidhalter/jedi-vim
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_cmd = 'Pyimport'
on_func = 'jedi#'
hook_add = 'source $NVIM_PLUGINS/jedi.vim'
# hook_source = '''
#   # call jedi#configure_call_signatures()
# '''

# Stylus .styl
# https://github.com/shirohana/vim-stylus
[[plugins]]
repo = 'shirohana/vim-stylus'
depends = ['vim-css3-syntax']
on_ft = 'stylus'

# TOML .toml
# https://github.com/cespare/vim-toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Vue .vue
# https://github.com/posva/vim-vue
# [[plugins]]
# repo = 'posva/vim-vue'
# depends = ['html5.vim', 'vim-pug', 'vim-javascript', 'vim-css3-syntax', 'vim-stylus']
# on_ft = 'vue'
