# ================================
# Appearance
# ================================

# Cursorword
# https://github.com/itchyny/vim-cursorword
[[plugins]]
repo = 'itchyny/vim-cursorword'
lazy = 0
hook_add = '''
  autocmd MyAutoCmd FileType nerdtree let b:cursorword = 0
'''

# lualine.nvim
# https://github.com/nvim-lualine/lualine.nvim
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# lazy = 0
# hook_add = 'source $NVIM_PLUGINS/lualine.rc.lua'

# ================================
# File Navigation
# ================================

# ZFZ
# https://github.com/junegunn/fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --bin'
# We need only executable
merged = 0
lazy = 1
[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FzfAg', 'Files', 'GFiles', 'Buffers', 'Ag', 'Tags', 'BTags', 'Marks', 'Windows', 'History:', 'Maps', 'Filetypes']
hook_source = 'source $NVIM_PLUGINS/fzf.vim'

# ================================
# Moving & Searching
# ================================

# Incsearch
# https://github.com/haya14busa/incsearch.vim
[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_func = 'incsearch#'
[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'vim-easymotion']
on_map = '<Plug>(incsearch-easymotion-'
[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = 'incsearch.vim'
on_map = '<Plug>(incsearch-fuzzy-'

# ================================
# Editing
# ================================

# EditorConfig
# https://github.com/editorconfig/editorconfig-vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_event = 'InsertEnter'
hook_add = '''
  let g:EditorConfig_disable_rules = [
    \ 'insert_final_newline',
    \ 'trim_trailing_whitespace',
    \ ]
'''

# Fugitive
# https://github.com/tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Git'
on_event = 'BufEnter'

# Peekaboo
# https://github.com/junegunn/vim-peekaboo
[[plugins]]
repo = 'junegunn/vim-peekaboo'
lazy = 1
hook_add = '''
  autocmd MyAutoCmd BufEnter * let b:peekaboo_on = 1
  let g:peekaboo_delay = 1750
'''

# Signature
# https://github.com/kshenoy/vim-signature
[[plugins]]
repo = 'kshenoy/vim-signature'
on_event = 'BufEnter'
