# ================================
# Appearance
# ================================

# Cursorword
# https://github.com/itchyny/vim-cursorword
[[plugins]]
repo = 'itchyny/vim-cursorword'
lazy = 0
hook_add = '''
  autocmd MyAutoCmd FileType nerdtree let b:cursorword = 0
'''

# lualine.nvim
# https://github.com/nvim-lualine/lualine.nvim
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# lazy = 0
# hook_add = 'source $NVIM_PLUGINS/lualine.rc.lua'

# ================================
# File Navigation
# ================================

# ZFZ
# https://github.com/junegunn/fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --bin'
# We need only executable
merged = 0
lazy = 1
[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FzfAg', 'Files', 'GFiles', 'Buffers', 'Ag', 'Tags', 'BTags', 'Marks', 'Windows', 'History:', 'Maps', 'Filetypes']
hook_source = 'source $NVIM_PLUGINS/fzf.vim'

# ================================
# Moving & Searching
# ================================

# Hop
# https://github.com/phaazon/hop.nvim
[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = 'source $NVIM_PLUGINS/hop.rc.lua'

# Incsearch
# https://github.com/haya14busa/incsearch.vim
[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_func = 'incsearch#'
[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'vim-easymotion']
on_map = '<Plug>(incsearch-easymotion-'
[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = 'incsearch.vim'
on_map = '<Plug>(incsearch-fuzzy-'

# ================================
# Editing
# ================================

# EditorConfig
# https://github.com/editorconfig/editorconfig-vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_event = 'InsertEnter'
hook_add = '''
  let g:EditorConfig_disable_rules = [
    \ 'insert_final_newline',
    \ 'trim_trailing_whitespace',
    \ ]
'''

# Fugitive
# https://github.com/tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Git'
on_event = 'BufEnter'

# Peekaboo
# https://github.com/junegunn/vim-peekaboo
[[plugins]]
repo = 'junegunn/vim-peekaboo'
lazy = 1
hook_add = '''
  autocmd MyAutoCmd BufEnter * let b:peekaboo_on = 1
  let g:peekaboo_delay = 1750
'''

# Signature
# https://github.com/kshenoy/vim-signature
[[plugins]]
repo = 'kshenoy/vim-signature'
on_event = 'BufEnter'

# SplitJoin
# https://github.com/AndrewRadev/splitjoin.vim
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_map = '<Plug>Splitjoin'
hook_add = '''
  let g:splitjoin_join_mapping = 0
  let g:splitjoin_split_mapping = 0
'''

# UltiSnips
# https://github.com/SirVer/ultisnips
[[plugins]]
repo = 'SirVer/ultisnips'
on_event = 'InsertEnter'
on_ft = 'snippets'
hook_add = '''
  let g:UltiSnipsSnippetDirectories = [$NVIM_SNIPPETS]
  let g:UltiSnipsEnableSnipMate = 0
  autocmd MyAutoCmd BufWritePost *.snippets call UltiSnips#RefreshSnippets()
'''

# ================================
# Utility
# ================================

# LSP
# https://github.com/neovim/nvim-lspconfig
# https://github.com/williamboman/nvim-lsp-installer
# https://github.com/tami5/lspsaga.nvim
# https://github.com/onsails/lspkind-nvim
[[plugins]]
repo = 'tami5/lspsaga.nvim'
hook_add = 'source $NVIM_PLUGINS/lspsaga.rc.lua'
[[plugins]]
repo = 'onsails/lspkind-nvim'
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['lspsaga.nvim', 'lspkind-nvim']
# on_ft = ['javascript', 'typescript', 'typescriptreact', 'typescript.tsx' 'python']
hook_add = 'source $NVIM_PLUGINS/lspconfig.rc.lua'
[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
depends = []
# hook_add = 'source $NVIM_PLUGINS/lsp-installer.rc.lua'

# CMP Completion
# https://github.com/hrsh7th/nvim-cmp
# https://github.com/hrsh7th/cmp-buffer
# https://github.com/hrsh7th/cmp-nvim-lsp
# https://github.com/L3MON4D3/LuaSnip
# https://github.com/ray-x/cmp-treesitter
# https://github.com/quangnguyen30192/cmp-nvim-ultisnips
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'ray-x/cmp-treesitter'
[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
depends = ['nvim-cmp']
hook_add = 'source $NVIM_PLUGINS/cmp-nvim-ultisnips.rc.lua'
[[plugins]]
repo = 'L3MON4D3/LuaSnip'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['cmp-buffer', 'cmp-treesitter', 'lspkind-nvim', 'nvim-lspconfig', 'L3MON4D3/LuaSnip']
# on_ft = ['javascript', 'typescript', 'typescriptreact', 'typescript.tsx' 'python']
hook_add = '''
  source $NVIM_PLUGINS/cmp.rc.lua
  set completeopt=menuone,noinsert,noselect
'''
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = ['nvim-lspconfig']
