# ================================
# Appearance
# ================================

# lualine.nvim
# https://github.com/nvim-lualine/lualine.nvim
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# lazy = 0
# hook_add = 'source $NVIM_PLUGINS/lualine.rc.lua'

# ================================
# File Navigation
# ================================

# ================================
# Moving & Searching
# ================================

# ================================
# Editing
# ================================

# EditorConfig
# https://github.com/editorconfig/editorconfig-vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_event = 'InsertEnter'
hook_add = '''
  let g:EditorConfig_disable_rules = [
    \ 'insert_final_newline',
    \ 'trim_trailing_whitespace',
    \ ]
'''

# Fugitive
# https://github.com/tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Git'
on_event = 'BufEnter'

# Peekaboo
# https://github.com/junegunn/vim-peekaboo
[[plugins]]
repo = 'junegunn/vim-peekaboo'
lazy = 1
hook_add = '''
  autocmd MyAutoCmd BufEnter * let b:peekaboo_on = 1
  let g:peekaboo_delay = 1750
'''

# Signature
# https://github.com/kshenoy/vim-signature
[[plugins]]
repo = 'kshenoy/vim-signature'
on_event = 'BufEnter'
