# ================================
# Plugin Manager
# ================================
# Dein https://github.com/Shougo/dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# ================================
# Appearance
# ================================

# Theme https://github.com/overcache/NeoSolarized
# Due to we need some customization, we cloned the scheme into
# `colors/NeoSolarized.vim`.

# TokyoNight https://github.com/folke/tokyonight.nvim
[[plugins]]
repo = 'folke/tokyonight.nvim'

# Airline https://github.com/vim-airline/vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
on_source = 'vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = "lua require 'plugins.airline'"

# Colorizer https://github.com/NvChad/nvim-colorizer.lua
[[plugins]]
repo = 'NvChad/nvim-colorizer.lua'

# DocumentColor https://github.com/mrshmllow/document-color.nvim
[[plugins]]
repo = 'mrshmllow/document-color.nvim'

# Cursorword https://github.com/itchyny/vim-cursorword
[[plugins]]
repo = 'itchyny/vim-cursorword'

# IndentBlankline https://github.com/lukas-reineke/indent-blankline.nvim
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

# Lualine https://github.com/nvim-lualine/lualine.nvim
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# hook_add = "lua require 'plugins.lualine'"

# # Scrollbar https://github.com/petertriho/nvim-scrollbar
[[plugins]]
repo = 'petertriho/nvim-scrollbar'

# ================================
# File Navigation
# ================================

# CtrlSpace https://github.com/vim-ctrlspace/vim-ctrlspace
[[plugins]]
repo = 'vim-ctrlspace/vim-ctrlspace'
# depends = ['fzf.vim']
hook_add = "lua require 'plugins.ctrlspace'"

# Fzf https://github.com/junegunn/fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --bin'
lazy = 1
merged = 0 # We installed only for executable
[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FzfAg', 'Files', 'GFiles', 'Buffers', 'Ag', 'Tags', 'BTags', 'Marks', 'Windows', 'History:', 'Maps', 'Filetypes']

# NvimTree https://github.com/kyazdani42/nvim-tree.lua
# [[plugins]]
# repo = 'kyazdani42/nvim-tree.lua'
# depends = ['nvim-web-devicons']

# NeoTree https://github.com/nvim-neo-tree/neo-tree.nvim
[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
depends = ['nui.nvim', 'nvim-web-devicons', 'plenary.nvim']

# Telescope https://github.com/nvim-telescope/telescope.nvim
# [[plugins]]
# repo = 'nvim-telescope/telescope.nvim'
# depends = ['plenary.nvim', 'telescope-fzf-native.nvim']

# TelescopeFzfNative https://github.com/nvim-telescope/telescope-fzf-native.nvim
[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
lazy = 1

# ================================
# Moving & Searching
# ================================

# EasyMotion https://github.com/easymotion/vim-easymotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = "lua require 'plugins.easymotion'"

# Hlslens https://github.com/kevinhwang91/nvim-hlslens
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

# Hop https://github.com/phaazon/hop.nvim
[[plugins]]
repo = 'phaazon/hop.nvim'

# ================================
# Editing
# ================================

# AutoPairs https://github.com/jiangmiao/auto-pairs
[[plugins]]
repo = 'jiangmiao/auto-pairs'
# on_event = 'InsertEnter'
hook_add = "lua require 'plugins.auto-pairs'"

# BetterWhitespace https://github.com/ntpeters/vim-better-whitespace
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
on_event = 'BufEnter'
hook_add = '''
let g:better_whitespace_operator = 0
let g:show_spaces_that_precede_tabs = 1
let g:strip_whitespace_confirm = 0
'''
hook_source = '''
augroup HanaBetterWhitespace
  autocmd!
  autocmd BufEnter * EnableStripWhitespaceOnSave
augroup END
'''

# Commentary https://github.com/tpope/vim-commentary
[[plugins]]
repo = 'tpope/vim-commentary'
on_map = '<Plug>Commentary'

# EasyAlign https://github.com/junegunn/vim-easy-align
[[plugins]]
repo = 'junegunn/vim-easy-align'
depends = ['vim-repeat']
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']

# SplitJoin https://github.com/AndrewRadev/splitjoin.vim
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_map = '<Plug>Splitjoin'
hook_add = '''
  let g:splitjoin_join_mapping = 0
  let g:splitjoin_split_mapping = 0
'''

# Surround https://github.com/kylechui/nvim-surround
[[plugins]]
repo = 'kylechui/nvim-surround'

# Undotree https://github.com/mbbill/undotree
[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'
hook_add = "lua require 'plugins.undotree'"

# https://github.com/SirVer/ultisnips
[[plugins]]
repo = 'SirVer/ultisnips'
# on_event = 'InsertEnter'
on_ft = 'snippets'
hook_add = '''
  let g:UltiSnipsSnippetDirectories = ["UltiSnips"]
  let g:UltiSnipsEnableSnipMate = 0
  " autocmd BufWritePost *.snippets call UltiSnips#RefreshSnippets()
'''

# VisualMulti https://github.com/mg979/vim-visual-multi
[[plugins]]
repo = 'mg979/vim-visual-multi'
hook_add = """
let g:VM_default_mappings = 0
let g:VM_maps = {}

let g:VM_maps['Find Under']                  = '<C-n>'
let g:VM_maps['Find Subword Under']          = '<C-n>'
let g:VM_maps["Select All"]                  = ';;A'
let g:VM_maps["Start Regex Search"]          = ';;/'
" let g:VM_maps["Add Cursor Down"]             = '<C-Down>'
" let g:VM_maps["Add Cursor Up"]               = '<C-Up>'
let g:VM_maps["Add Cursor At Pos"]           = ';;\'

let g:VM_maps["Visual Regex"]                = ';;/'
let g:VM_maps["Visual All"]                  = ';;A'
let g:VM_maps["Visual Add"]                  = ';;a'
let g:VM_maps["Visual Find"]                 = ';;f'
let g:VM_maps["Visual Cursors"]              = ';;c'

let g:VM_maps["Switch Mode"]                 = '<Tab>'

let g:VM_maps["Find Next"]                   = ']'
let g:VM_maps["Find Prev"]                   = '['
let g:VM_maps["Goto Next"]                   = '}'
let g:VM_maps["Goto Prev"]                   = '{'
let g:VM_maps["Seek Next"]                   = '<C-f>'
let g:VM_maps["Seek Prev"]                   = '<C-b>'
let g:VM_maps["Skip Region"]                 = 'q'
let g:VM_maps["Remove Region"]               = 'Q'
let g:VM_maps["Invert Direction"]            = 'o'
let g:VM_maps["Find Operator"]               = "m"
let g:VM_maps["Surround"]                    = 'S'
let g:VM_maps["Replace Pattern"]             = 'R'

" let g:VM_maps["Tools Menu"]                  = ';;`'
let g:VM_maps["Show Registers"]              = ';;"'
" let g:VM_maps["Case Setting"]                = ';;c'
let g:VM_maps["Toggle Whole Word"]           = ';;w'
let g:VM_maps["Transpose"]                   = ';;t'
let g:VM_maps["Align"]                       = ';;a'
let g:VM_maps["Duplicate"]                   = ';;d'
let g:VM_maps["Rewrite Last Search"]         = ';;r'
let g:VM_maps["Merge Regions"]               = ';;m'
let g:VM_maps["Split Regions"]               = ';;s'
let g:VM_maps["Remove Last Region"]          = ';;q'
let g:VM_maps["Visual Subtract"]             = ';;s'
let g:VM_maps["Case Conversion Menu"]        = ';;C'
let g:VM_maps["Search Menu"]                 = ';;S'

let g:VM_maps["Run Normal"]                  = ';;z'
let g:VM_maps["Run Last Normal"]             = ';;Z'
let g:VM_maps["Run Visual"]                  = ';;v'
let g:VM_maps["Run Last Visual"]             = ';;V'
let g:VM_maps["Run Ex"]                      = ';;x'
let g:VM_maps["Run Last Ex"]                 = ';;X'
let g:VM_maps["Run Macro"]                   = ';;@'
let g:VM_maps["Align Char"]                  = ';;<'
let g:VM_maps["Align Regex"]                 = ';;>'
let g:VM_maps["Numbers"]                     = ';;n'
let g:VM_maps["Numbers Append"]              = ';;N'
let g:VM_maps["Zero Numbers"]                = ';;0n'
let g:VM_maps["Zero Numbers Append"]         = ';;0N'
" let g:VM_maps["Shrink"]                      = ";;-"
" let g:VM_maps["Enlarge"]                     = ";;+"

" let g:VM_maps["Toggle Block"]                = ';;<BS>'
" let g:VM_maps["Toggle Single Region"]        = ';;<CR>'
" let g:VM_maps["Toggle Multiline"]            = ';;M'
"""

# ================================
# Git
# ================================

# Fugitive https://github.com/tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Git'
on_event = 'BufEnter'

# GitGutter https://github.com/airblade/vim-gitgutter
# [[plugins]]
# repo = 'airblade/vim-gitgutter'
# depends = ['vim-repeat']
# on_func = 'gitgutter#'
# # on_event = 'BufEnter'
# hook_add = "lua require 'plugins.gitgutter'"

# GitSigns https://github.com/lewis6991/gitsigns.nvim
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

# ================================
# Language Server
# ================================

# Fidget https://github.com/j-hui/fidget.nvim
[[plugins]]
repo = 'j-hui/fidget.nvim'

# LspColors https://github.com/folke/lsp-colors.nvim
[[plugins]]
repo = 'folke/lsp-colors.nvim'

# LspConfig https://github.com/neovim/nvim-lspconfig
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['lspkind-nvim', 'lspsaga.nvim']

# LspKind https://github.com/onsails/lspkind-nvim
[[plugins]]
repo = 'onsails/lspkind-nvim'

# LspLines https://git.sr.ht/~whynothugo/lsp_lines.nvim
[[plugins]]
repo = 'https://git.sr.ht/~whynothugo/lsp_lines.nvim'

# LspSaga https://github.com/tami5/lspsaga.nvim
[[plugins]]
repo = 'tami5/lspsaga.nvim'

# LspSignature https://github.com/ray-x/lsp_signature.nvim
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

# Mason https://github.com/williamboman/mason.nvim
[[plugins]]
repo = 'williamboman/mason.nvim'

# Navic https://github.com/SmiteshP/nvim-navic
[[plugins]]
repo = 'SmiteshP/nvim-navic'
depends = ['neovim/nvim-lspconfig']

# NullLs https://github.com/jose-elias-alvarez/null-ls.nvim
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim']

# Trouble https://github.com/folke/trouble.nvim
[[plugins]]
repo = 'folke/trouble.nvim'
depends = ['nvim-web-devicons']

# ================================
# Completion
# ================================

# Cmp https://github.com/hrsh7th/nvim-cmp
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['cmp-buffer', 'cmp-treesitter', 'lspkind-nvim', 'nvim-lspconfig', 'L3MON4D3/LuaSnip']

# CmpBuffer https://github.com/hrsh7th/cmp-buffer
[[plugins]]
repo = 'hrsh7th/cmp-buffer'

# CmpLuaSnip https://github.com/saadparwaiz1/cmp_luasnip
[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'

# CmpNvimLsp https://github.com/hrsh7th/cmp-nvim-lsp
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = ['nvim-lspconfig']

# CmpTreeSitter https://github.com/ray-x/cmp-treesitter
[[plugins]]
repo = 'ray-x/cmp-treesitter'

# CmpUltiSnips https://github.com/quangnguyen30192/cmp-nvim-ultisnips
[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
depends = ['ultisnips']

# LuaSnip https://github.com/L3MON4D3/LuaSnip
[[plugins]]
repo = 'L3MON4D3/LuaSnip'

# ================================
# Utility
# ================================

# Notify https://github.com/rcarriga/nvim-notify
[[plugins]]
repo = 'rcarriga/nvim-notify'
lazy =1

# Nui https://github.com/MunifTanjim/nui.nvim
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
lazy =1

# Plenary https://github.com/nvim-lua/plenary.nvim
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
lazy =1

# Repeat https://github.com/tpope/vim-repeat
[[plugins]]
repo = 'tpope/vim-repeat'
lazy = 1

# SymbolsOutline https://github.com/simrat39/symbols-outline.nvim
[[plugins]]
repo = 'simrat39/symbols-outline.nvim'

# TreeSitter https://github.com/nvim-treesitter/nvim-treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

# TreeSitterContext https://github.com/nvim-treesitter/nvim-treesitter-context
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
depends = ['nvim-treesitter']

# TreeSitterPlayground https://github.com/nvim-treesitter/playground
[[plugins]]
repo = 'nvim-treesitter/playground'
depends = ['nvim-treesitter']

# TreeSitterTextobjects https://github.com/nvim-treesitter/nvim-treesitter-textobjects
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
depends = ['nvim-treesitter']

# TreeSitterRainbow https://github.com/p00f/nvim-ts-rainbow
[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

# WebDevicons https://github.com/kyazdani42/nvim-web-devicons
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Wilder https://github.com/gelguy/wilder.nvim
[[plugins]]
repo = 'gelguy/wilder.nvim'
