# ================================
# Plugin Manager
# ================================
# Dein https://github.com/Shougo/dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# ================================
# Appearance
# ================================

# Theme https://github.com/overcache/NeoSolarized
# Due to we need some customization, we cloned the scheme into
# `colors/NeoSolarized.vim`.

# Lualine https://github.com/nvim-lualine/lualine.nvim
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = "lua require 'plugins.lualine'"

# Nvim-web-devicons https://github.com/kyazdani42/nvim-web-devicons
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# ================================
# File Navigation
# ================================

# NeoTree https://github.com/nvim-neo-tree/neo-tree.nvim
[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
depends = ['plenary.nvim', 'nvim-web-devicons', 'nui.nvim']
hook_add = "lua require 'plugins.neo-tree'"

# ================================
# Editing
# ================================

# AutoPairs https://github.com/jiangmiao/auto-pairs
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertEnter'
hook_add = "lua require 'plugins.auto-pairs'"

# BetterWhitespace https://github.com/ntpeters/vim-better-whitespace
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
on_event = 'BufEnter'
hook_add = '''
let g:better_whitespace_operator = 0
let g:show_spaces_that_precede_tabs = 1
let g:strip_whitespace_confirm = 0
'''
hook_source = '''
augroup HanaBetterWhitespace
  autocmd!
  autocmd BufEnter * EnableStripWhitespaceOnSave
augroup END
'''

# ================================
# Utility
# ================================

# Nui https://github.com/MunifTanjim/nui.nvim
[[plugins]]
repo = 'MunifTanjim/nui.nvim'

# Plenary https://github.com/nvim-lua/plenary.nvim
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# TreeSitter https://github.com/nvim-treesitter/nvim-treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = "lua require 'plugins.treesitter'"
hook_source = 'TSUpdate'
