local lspkind = require 'lspkind'

lspkind.init {
  -- mode = 'symbol',
  -- maxwidth = 50,
  symbol_map = {
    -- Text = '',
    Text = '',
    -- Method = '',
    Method = '',
    Function = '',
    Constructor = '',
    -- Field = 'ﰠ',
    Field = '',
    -- Variable = '',
    Variable = '',
    Class = 'ﴯ',
    Interface = '',
    -- Module = '',
    Module = '',
    -- Property = 'ﰠ',
    Property = '',
    Unit = '塞',
    Value = '',
    Enum = '',
    Keyword = '',
    -- Snippet = '',
    Snippet = '﬌',
    -- Color = '',
    Color = '',
    -- File = '',
    File = '',
    -- Reference = '',
    Reference = '',
    -- Folder = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = 'פּ',
    Event = '',
    Operator = 'ﬦ',
    TypeParameter = '',
  },
}
