local g = vim.g

g.VM_default_mappings = 0
g.VM_maps = {
  ['Find Under'] = '<C-n>',
  ['Find Subword Under'] = '<C-n>',
  ['Select All'] = ';;A',
  ['Start Regex Search'] = ';;/',
  -- ['Add Cursor Down'] = '<C-Down>',
  -- ['Add Cursor Up'] = '<C-Up>',
  ['Add Cursor At Pos'] = ';;\\',

  ['Visual Regex'] = ';;/',
  ['Visual All'] = ';;A',
  ['Visual Add'] = ';;a',
  ['Visual Find'] = ';;f',
  ['Visual Cursors'] = ';;c',

  ['Switch Mode'] = '<Tab>',

  ['Find Next'] = ']',
  ['Find Prev'] = '[',
  ['Goto Next'] = '}',
  ['Goto Prev'] = '{',
  ['Seek Next'] = '<C-f>',
  ['Seek Prev'] = '<C-b>',
  ['Skip Region'] = 'q',
  ['Remove Region'] = 'Q',
  ['Invert Direction'] = 'o',
  ['Find Operator'] = 'm',
  ['Surround'] = 'S',
  ['Replace Pattern'] = 'R',

  -- ['Tools Menu'] = ';;`',
  ['Show Registers'] = ";;'",
  -- ['Case Setting'] = ';;c',
  ['Toggle Whole Word'] = ';;w',
  ['Transpose'] = ';;t',
  ['Align'] = ';;a',
  ['Duplicate'] = ';;d',
  ['Rewrite Last Search'] = ';;r',
  ['Merge Regions'] = ';;m',
  ['Split Regions'] = ';;s',
  ['Remove Last Region'] = ';;q',
  ['Visual Subtract'] = ';;s',
  ['Case Conversion Menu'] = ';;C',
  ['Search Menu'] = ';;S',

  ['Run Normal'] = ';;z',
  ['Run Last Normal'] = ';;Z',
  ['Run Visual'] = ';;v',
  ['Run Last Visual'] = ';;V',
  ['Run Ex'] = ';;x',
  ['Run Last Ex'] = ';;X',
  ['Run Macro'] = ';;@',
  ['Align Char'] = ';;<',
  ['Align Regex'] = ';;>',
  ['Numbers'] = ';;n',
  ['Numbers Append'] = ';;N',
  ['Zero Numbers'] = ';;0n',
  ['Zero Numbers Append'] = ';;0N',
  -- ['Shrink'] = ';;-',
  -- ['Enlarge'] = ';;+',

  -- ['Toggle Block'] = ';;<BS>',
  -- ['Toggle Single Region'] = ';;<CR>',
  -- ['Toggle Multiline'] = ';;M',
}
